
insert into excluded_word values ("is");
insert into excluded_word values ("of");
insert into excluded_word values ("a");
insert into excluded_word values ("an");
insert into excluded_word values ("are");
insert into excluded_word values ("on");
insert into excluded_word values ("at");
insert into excluded_word values ("for");
insert into excluded_word values ("the");
insert into excluded_word values ("do");
insert into excluded_word values ("you");
insert into excluded_word values ("we");
insert into excluded_word values ("does");
insert into excluded_word values ("i");
insert into excluded_word values ("please");
insert into excluded_word values ("can");
insert into word_group (category,word) values (2,"what");
insert into word_group (category,word) values (1,"where");
insert into word_group (category,word) values (1,"why");
insert into word_group (category,word) values (1,"who");
insert into word_group (category,word) values (1,"when");
insert into word_group (category,word) values (1,"how");
insert into word_group values (2 ,"explain");
insert into word_group values (2 ,"clarify");
insert into word_group values (2 ,"justify");
insert into word_group values (2 ,"illustrate");
insert into word_group values (2 ,"define");
insert into word_group values (2 ,"definition");
insert into word_group values (2 ,"meaning");
insert into word_group values (2 ,"explanation");
insert into word_group values (3 ,"can");
insert into word_group values (3 ,"could");
insert into word_group values (3 ,"would");
insert into word_suffix values (1 ,"ing");
insert into word_suffix values (1 ,"s");
insert into word_suffix values (1 ,"tion");
